// frontend/src/data/courses.js
export const COURSES_DATABASE = [
  // Year 1 Courses
  {
    code: "WIX1001",
    name: "Introduction to Computing",
    credit: 3,
    prerequisites: [],
    year: 1,
    semester: 1,
  },
  {
    code: "WIX1002",
    name: "Fundamentals of Programming",
    credit: 4,
    prerequisites: [],
    year: 1,
    semester: 1,
  },
  {
    code: "MPU3113",
    name: "Ethnic Relations",
    credit: 2,
    prerequisites: [],
    year: 1,
    semester: 1,
  },
  {
    code: "WIA1002",
    name: "Data Structures",
    credit: 4,
    prerequisites: ["WIX1002"],
    year: 1,
    semester: 2,
  },
  {
    code: "WIX1003",
    name: "Database Systems",
    credit: 3,
    prerequisites: ["WIX1002"],
    year: 1,
    semester: 2,
  },
  {
    code: "GIG1012",
    name: "Philosophy and Current Issues",
    credit: 2,
    prerequisites: [],
    year: 1,
    semester: 2,
  },

  // Year 2 Courses
  {
    code: "WIX2001",
    name: "Computer Networks",
    credit: 3,
    prerequisites: ["WIX1001"],
    year: 2,
    semester: 1,
  },
  {
    code: "WIX2002",
    name: "Operating Systems",
    credit: 4,
    prerequisites: ["WIA1002"],
    year: 2,
    semester: 1,
  },
  {
    code: "WIX2003",
    name: "Web Development",
    credit: 3,
    prerequisites: ["WIX1002"],
    year: 2,
    semester: 1,
  },
  {
    code: "WIX3001",
    name: "Software Engineering",
    credit: 4,
    prerequisites: ["WIA1002", "WIX1003"],
    year: 2,
    semester: 2,
  },
  {
    code: "WIX3002",
    name: "Artificial Intelligence",
    credit: 3,
    prerequisites: ["WIA1002"],
    year: 2,
    semester: 2,
  },
  {
    code: "MPU3123",
    name: "Islamic Civilization",
    credit: 2,
    prerequisites: [],
    year: 2,
    semester: 2,
  },

  // Year 3 Courses
  {
    code: "WIX4001",
    name: "Final Year Project I",
    credit: 4,
    prerequisites: ["WIX3001"],
    year: 3,
    semester: 1,
  },
  {
    code: "WIX4002",
    name: "Machine Learning",
    credit: 3,
    prerequisites: ["WIX3002"],
    year: 3,
    semester: 1,
  },
  {
    code: "WIX4003",
    name: "Cloud Computing",
    credit: 3,
    prerequisites: ["WIX2001"],
    year: 3,
    semester: 1,
  },
  {
    code: "WIX4004",
    name: "Final Year Project II",
    credit: 4,
    prerequisites: ["WIX4001"],
    year: 3,
    semester: 2,
  },
  {
    code: "WIX4005",
    name: "Big Data Analytics",
    credit: 3,
    prerequisites: ["WIX3002", "WIX1003"],
    year: 3,
    semester: 2,
  },
  {
    code: "WIX4006",
    name: "Cybersecurity",
    credit: 3,
    prerequisites: ["WIX2001"],
    year: 3,
    semester: 2,
  },
];
