const ARTIFICIAL_INTELLIGENCE = "Artificial Intelligence";
const SOFTWARE_ENGINEERING = "Software Engineering";
const INFORMATION_SYSTEM = "Information System";
const COMPUTER_SYSTEM_AND_NETWORK = "Computer System and Network";
const MULTIMEDIA = "Multimedia";

const DEPARTMENTS = [
    ARTIFICIAL_INTELLIGENCE,
    SOFTWARE_ENGINEERING,
    INFORMATION_SYSTEM,
    COMPUTER_SYSTEM_AND_NETWORK,
    MULTIMEDIA
];

module.exports = {
    ARTIFICIAL_INTELLIGENCE,
    SOFTWARE_ENGINEERING,
    INFORMATION_SYSTEM,
    COMPUTER_SYSTEM_AND_NETWORK,
    MULTIMEDIA,
    DEPARTMENTS
};
